# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# 
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US
title: "So Simple IndieWeb Sample Site"
description: "A simple Jekyll theme with IndieWeb built in"
baseurl: # the subpath of your site, e.g. "/blog"
url: https://indieweb.bmann.ca # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/images/so-simple-site-logo.png" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: bmann # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

## REMOTE THEME SUPPORT
# plugins:
#  - jekyll-remote-theme
# remote_theme: https://github.com/bmann/so-simple-theme@indieweb-theme

## INDIEKIT
#
indiekit:
  micropub_server: bmann-indiekit.herokuapp.com
  auth_service: https://github.com/bmann



plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Boris Mann
  picture: /images/michael-rose-photo.jpg
  email:
  twitter: bmann
  links:
    - title: Twitter
      url: https://twitter.com/bmann
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/bmann
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/bmann
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/bmann
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
